import { notFound } from 'next/navigation';
import { ogContentType, ogSize, renderOgImage } from '@/lib/og';
import manifest from '@/lib/generated/posts-manifest.json';
import { formatPostDate, formatMonthLabel } from '@/lib/date';

// Edge runtime; post data comes from a build-time manifest because edge can't
// read the filesystem. The manifest is regenerated by `prebuild` / `predev`.
export const runtime = 'edge';
export const size = ogSize;
export const contentType = ogContentType;

type ManifestPost = {
  slug: string;
  title: string;
  date: string;
  tags?: string[];
};

const posts = (manifest.posts as ManifestPost[]) ?? [];

export function generateStaticParams() {
  return posts.map((post) => ({ slug: post.slug }));
}

export default function Image({ params }: { params: { slug: string } }) {
  const post = posts.find((p) => p.slug === params.slug);
  if (!post) notFound();

  return renderOgImage({
    title: post.title,
    subtitle: `${formatMonthLabel(post.date)} · ${formatPostDate(post.date)}`,
  });
}
